### PR TITLE
issue-7 Add return statement for charset func

### LINKED ISSUE #7: function charset - Not all code paths return a value
When this lib is used in a project with very restrictive typechecking (and it contains `"noImplicitReturns": true`) it will error out that charset function has implicit return.

### PR DESCRIPTION
**Pull request by Danielduel**
Fixes https://github.com/oakserver/media_types/issues/7

### CODE REVIEW

**Review by kitsonk — CHANGES_REQUESTED** [review]
I would prefer we `return undefined;` in both places in that function where that is the intention of the code.

**Comment by Danielduel** [comment]
@kitsonk I did 2 steps further and changed backticks in comments (because we are returning undefined non-implicitly) and unified returns for whole file.

**Comment by Danielduel** [comment]
Ah, wait... you are using those backticks for some docs renderer - I will add them again.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
